[debug] [2020-11-20T07:16:14.554Z] ----------------------------------------------------------------------
[debug] [2020-11-20T07:16:14.557Z] Command:       /usr/local/bin/node /usr/local/bin/firebase --project rymindrappnew apps:sdkconfig
[debug] [2020-11-20T07:16:14.557Z] CLI Version:   8.16.2
[debug] [2020-11-20T07:16:14.557Z] Platform:      darwin
[debug] [2020-11-20T07:16:14.558Z] Node Version:  v12.13.0
[debug] [2020-11-20T07:16:14.559Z] Time:          Fri Nov 20 2020 12:46:14 GMT+0530 (India Standard Time)
[debug] [2020-11-20T07:16:14.559Z] ----------------------------------------------------------------------
[debug] [2020-11-20T07:16:14.559Z] 
[debug] [2020-11-20T07:16:14.569Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-11-20T07:16:14.571Z] > authorizing via signed-in user
[debug] [2020-11-20T07:16:14.581Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/rymindrappnew:searchApps?pageSize=100  
 
[debug] [2020-11-20T07:16:15.422Z] <<< HTTP RESPONSE 403 {"vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Fri, 20 Nov 2020 07:16:15 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-11-20T07:16:15.422Z] <<< HTTP RESPONSE BODY {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2020-11-20T07:16:15.425Z] HTTP Error: 403, The caller does not have permission
[debug] [2020-11-20T07:16:15.861Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:38:12)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:41:35)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:476:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:476:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[error] 
[error] Error: Failed to list Firebase apps. See firebase-debug.log for more info.
